name: VeloDynamic-Paper
main: com.VeloDynamic.backend.VeloDynamicBackend
version: 1.0.0
api-version: 1.13
author: x08xNickelodeon
commands:
  dynamic:
    description: Dynamic command from Velocity proxy
    usage: /dynamic
    permission: velodynamic.command
permissions:
  velodynamic.command:
    description: Allows use of /dynamic
    default: op
